package com.celatus;

public enum UserAction {
    CHANGE_MASTER_PWD,
    COPY_IDENTIFIER,
    COPY_PASSWORD,
    DELETE_SELECTED,
    FULL_SCREEN,
    NEW_CATEGORY,
    NEW_PASSWORD,
    OPEN_SETTINGS,
    OPEN_WEBSITE,
    SAVE_DATABASE,
}

